project:
  type: website
  output-dir: docs

website:
  title: "dr-unyoung"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - the-journey.qmd
      - the-dissertation.qmd
      - the-defense.qmd
      - the-party.qmd
      - rsvp.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true



