---
title: "The Journey"
---

Completing this PhD has been one of the most challenging journeys I've embarked on. Over the course of 4 years, I juggled many responsibilities. I helped recruit patients, self-taught new analyses, wrote up papers, supervised interns, coordinated a department-wide study, and provided my statistical expertise to both colleagues and students. Not to mention, I navigated learning a new language, being far from family, building a new life in a new place, and growing into adulthood. I learned a lot about psychopathology as well as myself. There were many moments of frustration, such as dealing with reviewers comments, and accomplishments, such as getting a manuscript accepted by a journal. It is therefore with pride that I complete this journey. I couldn't have done it without the support of many, but I also couldn't have done it without my sheer determination and willpower. In the words of Snoop Dog (hahaha), "I want to thank me. I want to thank me for believing in me. I want to thank me for doing all this hard work."  

Some of you might be wondering, "what is your PhD about anyway?" Essentially, it is about pushing for a different way of conceptualizing and researching pscychopathology. The current way views disorders as separate categories and focuses on a limited set of symptoms in which that set of symptoms is the disorder. With the approaches I used (the transdiagnostic and network approaches), the idea is that psychopathology is not so naturally organized in discrete categories and arises from an interaction of not only symptoms but numerous other factors, many of which cut across disorders. Ultimately, it calls for a more dynamic, multifactorial, and holistic view of psychopathology, which may lead to better treatments. That's it in a nutshell!  

Lastly, some fun stats of what I did during my PhD:

- Wrote 5 research articles based on the Across study
- Published 4 of those research articles
- Supervised 35 interns
- Attended 6 international scientific conferences
- Learned and conducted three types of network analyses
- Had my hair cut and scalp gelled numerous times in the process of training my interns
- Improved my Dutch from B1 to B2/C1